name: 'realtime_upi_analytics'
version: '1.0.0'
config-version: 2

profile: 'realtime_upi_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  realtime_upi_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table

vars:
  start_date: '2024-01-01'

